# ndarrays Basics

In [2]:
import numpy as np
r1a = np.array([1,2,3])
print(type(r1a))

<class 'numpy.ndarray'>


In [3]:
print(r1a.shape)

(3,)


In [4]:
r1a[2]

3

In [8]:
r2a = np.array([[1,2,3],[4,5,6]])
print(r2a)

[[1 2 3]
 [4 5 6]]


In [10]:
ex1 = np.zeros((2,3))
print(ex1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ex2 = np.full((2,3), 8)
print(ex2)

[[8 8 8]
 [8 8 8]]


In [13]:
ex3 = np.eye(2,3)
print(ex3)

[[1. 0. 0.]
 [0. 1. 0.]]


In [14]:
ex4 = np.ones((2,3))
print(ex4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
ex5 = np.random.random((2,3))
print(ex5)

[[0.02121454 0.10614169 0.25120113]
 [0.38472612 0.4892738  0.02248683]]


# class 2

In [23]:
arr = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [22]:
print(arr[2,3])
print(arr[:2]) 
print(arr[:2, 1:3]) 

34
[[11 12 13 14]
 [21 22 23 24]]
[[12 13]
 [22 23]]


In [24]:
slice1 = arr[:, 2]
slice2 = arr[:, 2:3]
print(slice1, slice1.shape)
print(slice2, slice2.shape)

[13 23 33] (3,)
[[13]
 [23]
 [33]] (3, 1)


In [31]:
arr = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34], [41,42,43,44]])
col_idx = np.array([0,1,2,0])
row_idx = np.arange(4)
print(col_idx, row_idx)

[0 1 2 0] [0 1 2 3]


In [33]:
for col, row in zip(col_idx, row_idx):
    print(row, ',', col)
    print(arr[row, col])
    
print(arr[row_idx, col_idx])

0 , 0
11
1 , 1
22
2 , 2
33
3 , 0
41
[11 22 33 41]


In [34]:
print(arr)
arr[row_idx, col_idx] += 100
print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
[[111  12  13  14]
 [ 21 122  23  24]
 [ 31  32 133  34]
 [141  42  43  44]]


# Class 3

In [7]:
arr = np.array([[11, 12], [21,22], [31,32]])
# large_arr = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34], [41,42,43,44]])
print(arr)

[[11 12]
 [21 22]
 [31 32]]


In [10]:
filter = arr > 15
print(filter)
print(arr[filter])

[[False False]
 [ True  True]
 [ True  True]]
[21 22 31 32]


In [12]:
arr[arr %2 == 0 ] += 100
print(arr)

[[ 11 212]
 [ 21 222]
 [ 31 232]]


# Class 4


In [16]:
arr = np.array([11, 12], dtype=np.int64)
print(arr.shape)
print(arr.dtype)

(2,)
int64


In [17]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [18]:
print(x+y)
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]
[[322.1 324.1]
 [342.1 344.1]]


# class 5

In [19]:
arr = np.random.random((2,4))
print(arr)

[[0.69485619 0.42748467 0.20774287 0.9802856 ]
 [0.36344126 0.47350393 0.03221368 0.47713325]]


In [21]:
print(arr.mean())
print(arr.mean(0))
print(arr.mean(1))

0.45708267870042985
[0.52914872 0.4504943  0.11997827 0.72870942]
[0.57759233 0.33657303]


In [22]:
print(arr.sum())
print(arr.sum(0))

3.6566614296034388
[1.05829745 0.9009886  0.23995654 1.45741884]


In [23]:
print(np.median(arr, axis=1))

[0.56117043 0.41847259]


In [25]:
arr = np.random.random(10)
print(arr)

[0.36141033 0.87495378 0.30800859 0.09659062 0.89062277 0.92906032
 0.19766837 0.07740711 0.37461726 0.35549919]


In [26]:
cparr = np.array(arr)
print(cparr)

[0.36141033 0.87495378 0.30800859 0.09659062 0.89062277 0.92906032
 0.19766837 0.07740711 0.37461726 0.35549919]


In [29]:
sorted = cparr.sort()
print(cparr)
print(sorted)

[0.07740711 0.09659062 0.19766837 0.30800859 0.35549919 0.36141033
 0.37461726 0.87495378 0.89062277 0.92906032]
None


In [30]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]
